"""Initial migration

Revision ID: 48ca5374e96c
Revises: 
Create Date: 2026-07-10 16:20:02.187591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ca5374e96c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branches_code'), ['code'], unique=True)

    op.create_table('colleges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tnea_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('autonomous', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('colleges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_colleges_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_colleges_tnea_code'), ['tnea_code'], unique=True)

    op.create_table('import_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('import_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('community', sa.String(length=20), nullable=True),
    sa.Column('general_rank', sa.Integer(), nullable=True),
    sa.Column('community_rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('choice_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('choices_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('college_branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('nba_accredited', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('has_library', sa.Boolean(), nullable=True),
    sa.Column('has_sports', sa.Boolean(), nullable=True),
    sa.Column('has_transport', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fee_structure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('tuition_fee', sa.Float(), nullable=True),
    sa.Column('other_fees', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hostel_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('boys_hostel_available', sa.Boolean(), nullable=True),
    sa.Column('girls_hostel_available', sa.Boolean(), nullable=True),
    sa.Column('annual_fee', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('placement_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_companies', sa.Integer(), nullable=True),
    sa.Column('highest_package', sa.Float(), nullable=True),
    sa.Column('average_package', sa.Float(), nullable=True),
    sa.Column('placement_percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parameters_json', sa.Text(), nullable=True),
    sa.Column('results_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_saved_colleges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seat_matrix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_branch_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=10), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=True),
    sa.Column('filled_seats', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['college_branch_id'], ['college_branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yearly_cutoffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_branch_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=10), nullable=False),
    sa.Column('cutoff_mark', sa.Float(), nullable=True),
    sa.Column('community_rank', sa.Integer(), nullable=True),
    sa.Column('general_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['college_branch_id'], ['college_branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('yearly_cutoffs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_yearly_cutoffs_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_yearly_cutoffs_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yearly_cutoffs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yearly_cutoffs_year'))
        batch_op.drop_index(batch_op.f('ix_yearly_cutoffs_category'))

    op.drop_table('yearly_cutoffs')
    op.drop_table('seat_matrix')
    op.drop_table('user_saved_colleges')
    op.drop_table('recommendation_history')
    op.drop_table('placement_statistics')
    op.drop_table('hostel_information')
    op.drop_table('fee_structure')
    op.drop_table('facilities')
    op.drop_table('college_branches')
    op.drop_table('choice_lists')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('import_logs')
    with op.batch_alter_table('colleges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_colleges_tnea_code'))
        batch_op.drop_index(batch_op.f('ix_colleges_district'))

    op.drop_table('colleges')
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branches_code'))

    op.drop_table('branches')
    # ### end Alembic commands ###
